apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cassandra
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cassandra
    spec:
      serviceAccountName: instana-datastore-sa
      imagePullSecrets:
      - name: instana-pullsecret
      containers:
      - image: containers.instana.io/instana/release/product/cassandra:3.11.10_v0.18.0
        name: cassandra
        ports:
          - containerPort: 9042
        env:
          - name: CASSANDRA_LISTEN_ADDRESS
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        resources: {}
        securityContext:
          runAsUser: 0
        volumeMounts:
          - mountPath: /mnt/data
            name: cassandra-data
      volumes:
        - name: cassandra-data
          persistentVolumeClaim:
            claimName: cassandra-data
status: {}
