---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: cassandra-data
  namespace: instana-core
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ibmc-vpc-block-10iops-tier
  volumeMode: Filesystem
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   finalizers:
#   - kubernetes.io/pvc-protection
#   name: cassandra-logs
#   namespace: instana-core
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 50Gi
#   storageClassName: ibmc-vpc-block-10iops-tier
#   volumeMode: Filesystem
