apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: instana
    app.kubernetes.io/version: 219-0
  name: instana-operator-leader-election
  namespace: instana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "200"
    helm.sh/hook-weight: "200"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: instana-operator-leader-election
subjects:
  - kind: ServiceAccount
    name: instana-operator
    namespace: instana-operator
