apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: instana
    app.kubernetes.io/version: 219-0
  name: instana-operator
  namespace: instana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "200"
    helm.sh/hook-weight: "200"
spec:
  ports:
    - name: https-webhook
      port: 443
      protocol: TCP
      targetPort: https-webhook
  selector:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: instana
  type: ClusterIP
