apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:openshift:scc:anyuid
  namespace: instana-operator
  annotations:
    argocd.argoproj.io/sync-wave: "200"
    helm.sh/hook-weight: "200"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: instana-operator
  namespace: instana-operator
