apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: instana-pullsecret
  namespace: instana-units
  annotations:
    argocd.argoproj.io/sync-wave: "110"
    helm.sh/hook-weight: "110"
spec:
  data:
  - secretKey: instanaPullSecret
    remoteRef:
      key: a16f6899-cb75-2115-a618-f17ace53cf94
  refreshInterval: 24h
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: instana-pullsecret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/name: instana
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .instanaPullSecret | toString }}"
