apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster
  namespace: external-secrets
spec:
  provider:
    ibm:
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: ibmcloud-credentials
            namespace: kube-system
            key: ibmcloud_api_key
      serviceUrl: >-
        https://640fe8e5-7112-41f2-907e-a94256df6d64.us-south.secrets-manager.appdomain.cloud