apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: multiclusterhub-operator-pull-secret
  namespace: open-cluster-management-observability
  annotations:
    argocd.argoproj.io/sync-wave: "202"
    helm.sh/hook-weight: "202"
spec:
  data:
  - secretKey: openshiftPullSecret
    remoteRef:
      key: 251a59d8-b3b1-2a96-767a-1412f781346f
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: multiclusterhub-operator-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{{ .openshiftPullSecret | toString }}'
