apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odr-cluster-operator
spec:
  channel: stable-4.10
  installPlanApproval: Automatic
  name: odr-cluster-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace