apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: clickhouse
  name: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: clickhouse
    spec:
      serviceAccount: instana-datastore-sa
      imagePullSecrets:
      - name: instana-pullsecret
      containers:
      - image: containers.instana.io/instana/release/product/clickhouse:21.3.8.76_v0.10.0
        name: clickhouse
        resources: {}
        env:
          - name: ZOOKEEPER_HOST
            value: zookeeper-service
        ports:
          - containerPort: 9000
            name: clickhouse-9000
          - containerPort: 8123
            name: clickhouse-8123
        securityContext:
          runAsUser: 0
        volumeMounts:
          - mountPath: /mnt/data
            name: clickhouse-data
          - mountPath: /mnt/logs
            name: clickhouse-logs
      volumes:
        - name: clickhouse-logs
          persistentVolumeClaim:
            claimName: clickhouse-logs      
        - name: clickhouse-data
          persistentVolumeClaim:
            claimName: clickhouse-data
status: {}
