---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: instana-units-anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: tenant0-unit0
  namespace: instana-units
