# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: instana-core-anyuid
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: system:openshift:scc:anyuid
# subjects:
# - kind: ServiceAccount
#   name: instana-core
#   namespace: instana-core
# - kind: ServiceAccount
#   name: default
#   namespace: instana-core
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: instana-core-privileged
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: system:openshift:scc:privileged
# subjects:
# - kind: ServiceAccount
#   name: instana-core
#   namespace: instana-core
# - kind: ServiceAccount
#   name: default
#   namespace: instana-core
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: system:openshift:scc:anyuid
  namespace: instana-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: instana-core
  namespace: instana-core
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: system:openshift:scc:privileged
  namespace: instana-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: instana-core
  namespace: instana-core
