---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: instana-core-anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: instana-core
  namespace: instana-core
- kind: ServiceAccount
  name: default
  namespace: instana-core
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: instana-core-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: instana-core
  namespace: instana-core
- kind: ServiceAccount
  name: default
  namespace: instana-core
