apiVersion: instana.io/v1beta1
kind: Core
metadata:
  namespace: instana-core
  name: instana-core
  annotations:
    argocd.argoproj.io/sync-wave: "220"
    helm.sh/hook-weight: "220"
spec:
  baseDomain: apps.rhacm-gitops.ibmglb.ibm-gtmaa.dev
  imagePullSecrets:
    - name: instana-pullsecret
  emailConfig:
    smtpConfig:
      from: smtp@example.com
      host: smtp.example.com
      port: 465
      useSSL: true
  enableNetworkPolicies: false
  resourceProfile: large
  agentAcceptorConfig:
    host: ingress-instana.apps.rhacm-gitops.ibmglb.ibm-gtmaa.dev
    port: 443
  datastoreConfigs:
    - type: cassandra
      addresses:
        - cassandra-service.instana-core.svc.cluster.local
    - type: cockroachdb
      addresses:
        - cockroachdb-service.instana-core.svc.cluster.local
    - type: clickhouse
      addresses:
        - clickhouse-service.instana-core.svc.cluster.local
    - type: elasticsearch
      addresses:
        - elasticsearch-service.instana-core.svc.cluster.local
    - type: kafka
      addresses:
        - kafka-service.instana-core.svc.cluster.local
  rawSpansStorageConfig:
    pvcConfig:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 2Gi
      storageClassName: ocs-storagecluster-cephfs 
