apiVersion: instana.io/v1beta1
kind: Core
metadata:
  namespace: instana-core
  name: instana-core
  annotations:
    argocd.argoproj.io/sync-wave: "220"
    helm.sh/hook-weight: "220"
spec:
  baseDomain: apps.rhacm-gitops.ibmglb.ibm-gtmaa.dev
  imagePullSecrets:
    - name: instana-pullsecret
  emailConfig:
    smtpConfig:
      from: smtp@example.com
      host: smtp.example.com
      port: 465
      useSSL: true
  # enableNetworkPolicies: false
  resourceProfile: large
  agentAcceptorConfig:
    host: ingress-instana.apps.rhacm-gitops.ibmglb.ibm-gtmaa.dev
    port: 443
  datastoreConfigs:
    - addresses:
        - cassandra-service.instana-core.svc.cluster.local
      ports:
        - name: tcp
          port: 9042
      schemas:
        - spans
        - metrics
        - profiles
      type: cassandra
    - addresses:
        - clickhouse-service.instana-core.svc.cluster.local
      clusterName: local
      ports:
        - name: tcp
          port: 9000
        - name: http
          port: 8123
      schemas:
        - application
        - logs
      type: clickhouse
    - addresses:
        - cockroachdb-service.instana-core.svc.cluster.local
      ports:
        - name: tcp
          port: 26257
      schemas:
        - butlerdb
        - tenantdb
        - sales
      type: cockroachdb
    - addresses:
        - elasticsearch-service.instana-core.svc.cluster.local
      clusterName: onprem_onprem
      ports:
        - name: tcp
          port: 9300
        - name: http
          port: 9200
      schemas:
        - metadata_ng
      type: elasticsearch
    - addresses:
        - kafka-service.instana-core.svc.cluster.local
      ports:
        - name: tcp
          port: 9092
      schemas:
        - ingress
        - global-ingress
      type: kafka
  rawSpansStorageConfig:
    pvcConfig:
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 2Gi
      storageClassName: ocs-storagecluster-cephfs 
  featureFlags:
    - enabled: false
      name: aggregator.available

# %{ if toggle("config.selfhosted.docker.aggregator.available", "false") == "true" }
# beeInstanaConfig:
#   host: ${ datastore.beeinstana.metrics.host }
#   port: ${ datastore.beeinstana.metrics.port }
#   basePath: ${ datastore.beeinstana.metrics.base_path }
# %{ endif }