apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: instana-core
  annotations:
    argocd.argoproj.io/sync-wave: "210"
    helm.sh/hook-weight: "210"
spec:
  data:
  - secretKey: instanaAgentKey
    remoteRef:
      # key: 4d18cfd7-84ee-dbb5-7567-cfef62391453
      key: 8539f598-8991-10b2-9d2e-fc67730d7f57
  - secretKey: instanaSalesKey
    remoteRef:
      key: 8147ba92-e890-167a-2c4b-0f15836097e8
  - secretKey: instanaAdminPassword
    remoteRef:
      key: 56f15e37-51bb-3138-7c6b-14128ca242fc
  - secretKey: instanaLicense
    remoteRef:
      key: b60a3245-667f-449e-c608-fcde18d8d9ec
  - secretKey: instanaDHParams
    remoteRef:
      key: 73788be7-f584-8e1e-2abb-cf2b84f5c625
  - secretKey: instanaToken
    remoteRef:
      key: 67ce1331-37f0-5eb9-cf23-210225de7b82
  - secretKey: instanaSPKeyPass
    remoteRef:
      key: f5519039-6013-4f43-2217-8335c7356256
  - secretKey: instanaSPPem
    remoteRef:
      key: 4a8985a4-9bdd-7b42-4b68-e26e9451e74a
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: instana-core
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/name: instana
      type: Opaque
      data:
        config.yaml: |-
          adminPassword: "{{ .instanaAdminPassword | toString }}"
          dhParams: |
            {{ .instanaDHParams | toString }}
          downloadKey: "{{ .instanaAgentKey | toString }}"
          salesKey: "{{ .instanaSalesKey | toString }}"
          tokenSecret: "{{ .instanaToken | toString }}"
          serviceProviderConfig:
            keyPassword: "{{ .instanaSPKeyPass | toString }}"
            pem: |-
              {{ .instanaSPPem | toString }}

