
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: instana-tls
  annotations:
    argocd.argoproj.io/sync-wave: "210"
    helm.sh/hook-weight: "210"
spec:
  data:
  - secretKey: tlsCrt
    remoteRef:
      key: f3f22260-f404-ab95-f056-1fe1cc79699e
  - secretKey: tlsKey
    remoteRef:
      key: 811b4a46-8931-ce31-7958-16168d9f4e1c
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: instana-tls
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/name: instana
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .tlsCrt | toString }}"
        tls.key: "{{ .tlsKey | toString }}"
