
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: instana-service-provider
  annotations:
    argocd.argoproj.io/sync-wave: "210"
    helm.sh/hook-weight: "210"
spec:
  data:
  - secretKey: instanaSPKeyPass
    remoteRef:
      key: f5519039-6013-4f43-2217-8335c7356256
  - secretKey: instanaSPPem
    remoteRef:
      key: 4a8985a4-9bdd-7b42-4b68-e26e9451e74a
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: instana-service-provider
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/name: instana
      type: Opaque
      data:
        sp.key.pass: "{{ .instanaSPKeyPass | toString }}"
        sp.pem: "{{ .instanaSPPem | toString }}"
