apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-multicluster-orchestrator-operator
  namespace: openshift-operators
spec:
  channel: stable-4.10
  installPlanApproval: Automatic
  name: odf-multicluster-orchestrator
  source: redhat-operators
  sourceNamespace: openshift-marketplace