apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: elasticsearch
    spec:
      serviceAccountName: instana-datastore-sa
      imagePullSecrets:
      - name: instana-pullsecret
      containers:
      - image: containers.instana.io/instana/release/product/elasticsearch:7.16.3_v0.13.0
        name: elasticsearch7
        env:
          - name: LISTEN_ADDR
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
          - containerPort: 9200
            name: elastic-9200
          - containerPort: 9300
            name: elastic-9300
        resources: {}
        securityContext:
          privileged: true
          runAsUser: 0
status: {}
